{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sentinel.fullname" . }}-api
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
    component: api
spec:
  selector:
    matchLabels:
      {{- include "sentinel.selectorLabels" . | nindent 6 }}
      component: api
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
