{{- if .Values.agent.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sentinel.fullname" . }}-agent
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
    component: agent
{{- end }}
