FROM golang:1.23-alpine AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /sentinel-agent ./cmd/sentinel-agent

FROM gcr.io/distroless/static-debian12
COPY --from=builder /sentinel-agent /sentinel-agent
ENTRYPOINT ["/sentinel-agent"]
