FROM golang:1.25-alpine AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /sentinel-chain-app ./cmd/sentinel-chain-app

FROM gcr.io/distroless/static-debian12
COPY --from=builder /sentinel-chain-app /sentinel-chain-app
ENTRYPOINT ["/sentinel-chain-app"]
